# Generated by Django 6.0.5 on 2026-05-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('bn_name', models.CharField(default='', max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('geojson', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GeoFeatureDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('geometry', models.JSONField()),
                ('properties', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perimeter_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('area_km2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GeoFeatureDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('geometry', models.JSONField()),
                ('properties', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perimeter_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('area_km2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GeoFeatureUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('geometry', models.JSONField()),
                ('properties', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perimeter_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('area_km2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GeoFeatureUpazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('geometry', models.JSONField()),
                ('properties', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perimeter_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('area_km2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('bn_name', models.CharField(default='', max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('geojson', models.IntegerField(default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='geo_locations.divisions')),
            ],
        ),
        migrations.CreateModel(
            name='Upazilas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('bn_name', models.CharField(default='', max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('geojson', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazila', to='geo_locations.districts')),
            ],
        ),
        migrations.CreateModel(
            name='Unions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('bn_name', models.CharField(default='', max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('geojson', models.IntegerField(default=0)),
                ('upazila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='union', to='geo_locations.upazilas')),
            ],
        ),
    ]
