# Generated by Django 6.0.5 on 2026-05-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofeaturebangladesh',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeaturebangladesh',
            name='perimeter_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeaturedistrict',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeaturedistrict',
            name='perimeter_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeaturedistrictsmall',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeaturedistrictsmall',
            name='perimeter_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeaturedivision',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeaturedivision',
            name='perimeter_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeaturedivisionsmall',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeaturedivisionsmall',
            name='perimeter_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeatureunion',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeatureunion',
            name='perimeter_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeatureunionsmall',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeatureunionsmall',
            name='perimeter_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeatureupazila',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeatureupazila',
            name='perimeter_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeatureupazilasmall',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='geofeatureupazilasmall',
            name='perimeter_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
