# Generated by Django 6.0.5 on 2026-05-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_locations', '0002_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Browser'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device'),
        ),
    ]
